services:
  - type: web
    name: budgethub
    env: python
    region: oregon
    plan: free
    branch: main
    buildCommand: >
      pip install -r requirements.txt &&
      python manage.py collectstatic --noinput &&
      python manage.py migrate
    startCommand: gunicorn config.wsgi:application
    envVars:
      - key: DEBUG
        value: false
      - key: DJANGO_SETTINGS_MODULE
        value: config.settings
      - key: PYTHON_VERSION
        value: 3.11.0
